chore: azurite test failing due to API versions mismatch (#8060)
The azurite tests were failing with the following error:

ERROR: Can't connect to cloud provider: The API version 2025-07-05 is
not supported by Azurite. Please upgrade Azurite to latest version and
retry. If you are using Azurite in Visual Studio, please check you have
installed latest Visual Studio patch. Azurite command line parameter
\"--skipApiVersionCheck\" or Visual Studio Code configuration \"Skip Api
Version Check\" can skip this error.

Added the `--skipApiVersionCheck` option to the Azurite server we run,
which avoids this issue.

This problem was already reported in the Azurite community at
https://github.com/azure/azurite/issues/2564

Closes #8059

Signed-off-by: Jonathan Gonzalez V. <jonathan.gonzalez@enterprisedb.com>
(cherry picked from commit f802c3f810732c4aeab9537a6d77504beccceee9)