Define a TMPDIR environment variable pointing to a writeable directory
Tools like `barman` crash when `tempfile.mkdtemp` cannot find any
writeable directory amongst the list of "usual suspects" (`/tmp`,
`/var/tmp`, `/usr/tmp`, etc).

```
File "/usr/lib/python3.11/tempfile.py", line 454, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 447, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 362, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/srv/app']
```

As the operator creates the PG pods with `ReadOnlyRootFilesystem` set to
`true`, setting this environment variable will allow barman to write its
temporary files under `/controller` (we could argue it could be `/run`,
as the same volume is mounted to both mountpoints).
This is due to CPyhon considering on this [environment variable](https://github.com/python/cpython/blob/main/Lib/tempfile.py#L163-L165)
to add potential temporary directories to try when running `mkdtemp` or
`mktemp`.

```python
postgres@postgresql-test-2:/srv/app$ python3
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getenv('TMPDIR')
>>> import tempfile
>>> tempfile.mkdtemp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/tempfile.py", line 512, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 265, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 454, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 447, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 362, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/srv/app']
>>>
postgres@postgresql-test-2:/srv/app$ export TMPDIR=/controller
postgres@postgresql-test-2:/srv/app$ python3
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> tempfile.mkdtemp()
'/controller/tmpvn9860lm'
```

I've also opted to to not adding it to the list of reserved variables,
as it does not have anything to do with PG itself, and thus could be
overriden from the chart, but this is really not out of strong
conviction.

Signed-off-by: Balthazar Rouberol <br@imap.cc>