docs: add missing scheme for s3 endpoint example (#1429)
Add `https://` scheme the S3-compatible example for Linode.

Using a value without scheme here will result in a failure with a log message:
```
ERROR: Barman cloud backup exception: Invalid endpoint: s3.example.com
```

All the other sample `endpointURL`s on this page already have a scheme.

Signed-off-by: Milas Bowman <devnull@milas.dev>
(cherry picked from commit d41fba6f60148386414149975e6d659f765d29ea)