fix(plugin): handle empty response in sync-sequences plugin command (#4346)
Fix the `kubectl-cnpg subscription sync-sequences` execution when the
source or the destination database has no sequence.

Previously, the command was failing with the following error:

Error: while getting sequences status from the source database: while
decoding JSON output: unexpected end of JSON input

Closes #4345

Signed-off-by: Marco Nenciarini <marco.nenciarini@enterprisedb.com>
(cherry picked from commit aed4fd069e1f04f8a52991a72db2f932fd58ad31)